borisbu/OctoRelay

octoprint_octorelay/__init__.py

This fixes an issue with relays not being turned on when a print starts.
I use OctoRelay to control only 1 relay (Pin #18). However there are 7 other placeholder/default configs. One of these placeholder configs happens to also be configured for Pin #18, and has `inverted_output: True` set. After `print_started()` turns on my relay, it then processes the placeholder config and flips it off again.
The debug logs show the conflicting pin configs:
```
settings for r1: {'active': True, 'relay_pin': '18', 'inverted_output': False,
settings for r2: {'active': False, 'relay_pin': 17, 'inverted_output': True,
settings for r3: {'active': False, 'relay_pin': 18, 'inverted_output': True,
[....]
```
_Side note: There seems to be some type confusion. Inactive configs have relay_pin as a int, but …

Make `print_started()` only process "active" relay configs.

---

.github/workflows/CI.yaml
octoprint_octorelay/test__init.py

- Removing excessive statements from the tests
- Ensuring that some methods are not called conditionally
- Testing the exception handling
- Coverage `100%`
- Clarification for the CI tests naming
- Testing against Python up to `3.11`
- Testing against OctoPrint down to `1.8` (compatibility)

Improving and refactoring the tests

---

.github/workflows/CI.yaml

It turned out that #89 did not actually force to install OctoPrint 1.8.
This PR should fix this.
Tested versions:
- OctoPrint 1.8: on Python 3.7–3.9
- OctoPrint 1.9: on Python 3.7-3.11

CI: ensure testing against OctoPrint 1.8

---

octoprint_octorelay/__init__.py
octoprint_octorelay/test__init.py

The issue originally fixed by @jneilliii in #44 
I'm cherry-picking it into another PR in order to release the fix separately.
Closes #96

Listing the required API param `pin`.

---

CHANGELOG.md
README.md
octoprint_octorelay/__init__.py
octoprint_octorelay/templates/octorelay_navbar.jinja2
octoprint_octorelay/test__init.py

Closes #51 
Approach: introducing a custom permission.
- Initially enabled for Admins and Users (Operators).
Constraints:
- Avoid showing the buttons
- Reject the API command `update`
- Avoid toggling relays having "ON initially on boot"
- Avoid toggling relays having "Auto ON/OFF before/after printing"

Prohibit operating relays for readonly users

---

CHANGELOG.md
README.md
octoprint_octorelay/__init__.py
octoprint_octorelay/static/js/octorelay.js
octoprint_octorelay/templates/octorelay_navbar.jinja2
octoprint_octorelay/test__init.py
ts/__snapshots__/octorelay.spec.ts.snap
ts/octorelay.spec.ts
ts/octorelay.ts

Closes #51 
Continuation of #99 
It turned out that `on_` events are happening outside the user context, so they don't have access to Permission.

Relay switching permission

---

CHANGELOG.md
octoprint_octorelay/__init__.py
octoprint_octorelay/const.py
setup.py

Just noticed that in some cases the values of the plugin settings may not appear in OctoPrint.
I have no idea why, but it figured out that keeping templates as inline return fixes this issue.

Hotfix: Reverting a const for templates.

---

.github/workflows/release.yaml
CHANGELOG.md
octoprint_octorelay/static/js/octorelay.js
ts/package.json
ts/stub/octorelay.ts
ts/tsconfig.build.json
ts/tsconfig.stub.json

Closes #115 
Continuation of #129 — QA revealed a need for a stub
⚠️ Breaking
Switching to ZIP-package distribution requires user to update the plugin TWICE.
After the first update there will be no control buttons in navbar which I consider a disruption of service, requiring a user's action to fix.
In order to minimise the confusion I'm making a stub showing a warning icon for attracting user's attention on the needed action, and a dialog explaining what to do.

JS: notification stub in sources

---

.github/workflows/CI.yaml
.github/workflows/release.yaml

Closes #130 
- OctoPrint 1.3 and 1.4 are not supported
This PR increases the release time by 15 seconds but it ensures compatibility of the plugin installation against OctoPrint 1.5-1.9 and Python 3.7-3.11 matrix

Testing actual compatibility

---

tests/test_driver.py
tests/test_init.py
tests/test_migrations.py

It's an addition and fix to #138 
This PR:
- avoids testing actual GPIO operation within the plugin's class (it's devoted to driver test)
- fixes the test of API commands
- brings a bit more organization to the imports in tests

No double testing of GPIO operation

---

CHANGELOG.md
octoprint_octorelay/__init__.py
tests/test_init.py

Closes #18 
This will only work for OctoPrint 1.9+
I decided to go without additional setting, a possibility of which (in part of its conditional appearance) is being [discussed on OctoPrint community forum](https://community.octoprint.org/t/binding-to-octoprint-version-or-feature-presence/53272/3). And also without any additional or configurable delay. If there will be an issue of a need I will add it later.

Feat: AutoConnect

---

CHANGELOG.md
octoprint_octorelay/__init__.py
tests/test_init.py

Closes #150 
- Consistently operating the relay settings.
- Less statements.

Using `merged=True` for getting settings

---

octoprint_octorelay/__init__.py
tests/test_init.py

Closes #150 
Due to performance issues [revealed](https://github.com/borisbu/OctoRelay/pull/161#issuecomment-1670301028) during the QA of #159 
Instead of reading each relay settings in a loop — read all once before the loop.

Read all relay settings once (fix performance)

---

.pylintrc
deploy.sh
deployAndRestart.sh
octoprint_octorelay/__init__.py
octoprint_octorelay/const.py
octoprint_octorelay/migrations.py
octoprint_octorelay/templates/octorelay_settings.jinja2
tests/snapshots/snap_test_templates.py
tests/test_init.py
tests/test_migrations.py
tests/test_templates.py
ts/bindings.spec.ts

This should make the plugin more flexible for implementing more reactions in the future.
Closes #28 
For each relay, instead of having these config props:
```
initial_value, auto_on_before_print, auto_off_after_print, auto_off_delay
```
I'm making a more generic object `rules` having entries matching the following events:
```
STARTUP, PRINTING_STARTED, PRINTING_STOPPED
```
Each of those entries is an object having following properties:
- `state` — the desired relay state in case of the event
- except `None` meaning "no action needed"
- `delay` — the delay for performing that action (seconds)
Thus, 
- `initial_value` becomes `bool` in `rules/STARTUP/state`
- `auto_on_before_print` becomes `True | None` in `rules/PRINTING_STARTED/state`
- `auto_off_after_print` becomes `False | None` in …

Feat: internal events and rules

---

README.md

Readme: Add downloads badge

---

octoprint_octorelay/__init__.py
octoprint_octorelay/migrations.py
tests/test_init.py
tests/test_migrations.py

Closes #180 
- General cleanup
- Consistency and neatness 
- Reducing the noise and the volume on the `info` (default) level
- Improve clarity and the volume on `debug` level (opt-in), making it easier to debug something if needed
- Starting and finishing the operation of the plugin — `info`
- Beginnings of handlers of user actions — `info`
- Clarifications on details or consequences of user actions — `debug`
- Successful ending of an operation — `debug`
- Beginning of a code branch (conditional code) — `debug`
- General tracing — `debug`

Organised logging

---

ts/octorelay.spec.ts
ts/octorelay.ts

Probably fixes #190 
This is the UX adjustment that removes the outside click listener from the popover, that might lead to confusion, making the popover disappear unexpectedly from the user's perspecive.

Removing the outside click listener for upcoming switch popover.

---

octoprint_octorelay/__init__.py
tests/test_init.py

Closes #153 
This feature makes the following improvements:
- it prevents the `SerialException` error appearance when turning the printer relay off,
- it prevents the redundant attempts to connect when there are no printers visible.

Disconnecting from the printer before when turning its relay off

---

octoprint_octorelay/__init__.py
octoprint_octorelay/exceptions.py
tests/test_init.py

Contributes to #164 
No breaking changes to the API yet, but preparing for introducing its new version by extracting the response shaping outta handlers. So the `on_api_command` method will be the only one who operates `flask`.
Handlers, on the other hand, are either return data OR raise exceptions.
For that, introducing also `HandlingException` class, accepting the HTTP status code that is supposed to be used for managing the response in case of an error raised during handling the request.
Preserving (for now) the original behaviour of `update` command, which in case of disabled relay responds with `status: error` instead of aborting.

Ref: API: Moving response shaping out of handlers

---

octoprint_octorelay/__init__.py
tests/test_init.py

Ref: Moving required params checks

---

octoprint_octorelay/__init__.py
octoprint_octorelay/listing.py
setup.py
tests/test_init.py
ts/helpers/actions.spec.ts
ts/helpers/actions.ts

Closes #164 
Introducing API parameter `version` or `v` (optional).
The default `version` falls back to `1` so the API keeps its original behaviour by default until the next major release.
- When requesting an action on relay, now calling it `subject` instead of `pin`.
- When receiving the relay state, now calling it `status` instead of `result` or `active`.
- When requesting the state of disabled relay now responding with `400` HTTP code instead of `status: False`
- When updating or cancelling something, there is no more `status: "ok" | "error"`, the `status` now always means the relay state (boolean), while error response is supplied via HTTP code.
| Method | Inputs before | Inputs after |
|--------|--------|--------|
| update | `pin, target` | `subject, target` |
| getStatus | `pin` | …

Feat: API v2

---

octoprint_octorelay/__init__.py
octoprint_octorelay/_version.py
setup.py

This should prevent issues like #284 
https://stackoverflow.com/a/48777286
https://setuptools.pypa.io/en/latest/references/keywords.html

Prevent installations on environments having unsupported Python versions

---

CHANGELOG.md
octoprint_octorelay/driver.py
tests/test_driver.py

If relay is inverted, `gpiozero` sets its initial value to `false`, which turns it on, because `false` is the default initial value in docs:
https://gpiozero.readthedocs.io/en/latest/api_output.html#led

Avoid excessive switches on startup

---

ui/__snapshots__/qa.spec.ts.snap
ui/helpers/countdown.spec.ts
ui/helpers/countdown.ts
ui/mocks/lodash.ts
ui/octorelay.spec.ts
ui/package.json
ui/tsconfig.json
ui/types/OctoPrint.d.ts
ui/yarn.lock

addition to #319 
This improves the performance on number formatting being instantiated in a cycle.
The approach is to use the lodash.memoize() which is integrated within OctoPrint, v3.10.1
```
✓ intl.bench.ts (2) 2610ms
✓ Intl performance (2) 2608ms
name                             hz     min     max    mean     p75     p99    p995    p999     rme  samples
· new Intl.NumberFormat     89,964.12  0.0097  0.8449  0.0111  0.0114  0.0166  0.0256  0.0648  ±1.09%    44983
· memoized               4,063,946.37  0.0002  0.8680  0.0002  0.0002  0.0003  0.0004  0.0010  ±0.76%  2031974   fastest
BENCH  Summary
memoized - intl.bench.ts > Intl performance
45.17x faster than new Intl.NumberFormat
```

Performance tuning for number formatting

---

.github/workflows/release.yaml

Closes #328 
using modern attach action
https://github.com/softprops/action-gh-release?tab=readme-ov-file#%EF%B8%8F-uploading-release-assets

Upgrading release workflow

---

.github/workflows/CI.yaml

There was a breaking change to setuptools, that affects the CI in #345 and #348 
Proper fix requires investigation and migrating to a different setup approach

CI: downgrading `setuptools`

---

.github/workflows/CI.yaml

OctoPrint 1.11 now supports Python 3.13
https://github.com/OctoPrint/OctoPrint/releases/tag/1.11.0

Supporting Python 3.13
