- octoprint_octorelay/templates/octorelay_navbar.jinja2
In order to make it feel like the rest of the menu items.
> Pointer cursor for menu icons

- octoprint_octorelay/__init__.py
Added GPIO polling thread to correctly show
pin statuses when multiple scripts/plugins
can change them.
> added GPIO polling thread

- LICENSE
Applying the Recommended Community Standards.
According to this line:
https://github.com/borisbu/OctoRelay/blob/5a940f5fa253930341db3ae0e864bb691fb39a5e/setup.py#L34
> Creating the LICENSE file

- CHANGELOG.md
- README.md
- I'm extracting the changelog to a dedicated file
- Also updating the Readme file to improve clarity and reflect the current state
> Making Changelog, Updating Readme

- octoprint_octorelay/__init__.py
Making a pre-release channel in accordance with this article:
https://github.com/cp2004/OctoPrint-Knowledge/blob/main/release-channels.md
Closes #66
> Making a pre-release channel configuration.

- CHANGELOG.md
- setup.py
- Changelog entry
- Version bump
> Preparing v1.3.0 release

- CHANGELOG.md
- LICENSE
- README.md
- octoprint_octorelay/__init__.py
- setup.py
Merging the recent changes from `develop` to `master`
- #64 
- #69 
- #67 
- #70
> Releasing v1.3.0

- CHANGELOG.md
- octoprint_octorelay/__init__.py
- setup.py
> Releasing `1.4.1`

- CHANGELOG.md
- octoprint_octorelay/__init__.py
> Requiring Python 3.7

- README.md
I made a mistake in https://github.com/borisbu/OctoRelay/pull/69 landed in v1.3.0 release.
"OS Command" is actually an optional event handler
> Fix incorrect description of the OS command setting.

- .github/workflows/CI.yaml
- octoprint_octorelay/__init__.py
- octoprint_octorelay/test__init.py
Closes #65 
Coverage — 99% ✅ 
I also made tests independent on each other by replacing lifecycle method.
Info:
- Mock assertions doc: https://docs.python.org/3/library/unittest.mock.html#the-mock-class
- `os` mocking: https://itecnote.com/tecnote/python-the-best-way-to-mock-os-system-for-unit-test-pytest/
> Complete Python tests 

- CHANGELOG.md
- octoprint_octorelay/__init__.py
- octoprint_octorelay/test__init.py
- setup.py
> Releasing 2.0.1

- .github/workflows/CI.yaml
- README.md
> Coveralls integration

- .github/workflows/CI.yaml
- README.md
- octoprint_octorelay/test__init.py
> Merging develop

- CHANGELOG.md
- octoprint_octorelay/__init__.py
- octoprint_octorelay/test__init.py
- setup.py
> Releasing 2.0.2

- CHANGELOG.md
- README.md
- octoprint_octorelay/__init__.py
- octoprint_octorelay/static/js/octorelay.js
- octoprint_octorelay/templates/octorelay_navbar.jinja2
- octoprint_octorelay/test__init.py
- setup.py
- ts/__snapshots__/octorelay.spec.ts.snap
- ts/octorelay.spec.ts
- ts/octorelay.ts
> Releasing 2.1.0

- CHANGELOG.md
- README.md
- octoprint_octorelay/__init__.py
- octoprint_octorelay/test__init.py
- setup.py
> Releasing 2.2.0

- octoprint_octorelay/__init__.py
> Naming: relay state instead of LED one

- octoprint_octorelay/__init__.py
> Ref: replacing `dict()` with curly braces.

- octoprint_octorelay/__init__.py
- octoprint_octorelay/const.py
> Using f-strings instead of `.format()`

- .github/workflows/codeql.yml
Trying code quality static check
> CodeQL check

- octoprint_octorelay/__init__.py
- octoprint_octorelay/test__init.py
Closes #104 
Enforcing stricter boolean operations and comparisons
> Ensure booleans: initialisations and strict comparison

- .github/workflows/codeql.yml
- CHANGELOG.md
- octoprint_octorelay/__init__.py
- octoprint_octorelay/const.py
- octoprint_octorelay/test__init.py
- setup.py
Closes #113 
Closes #104 
- #119 
- #120 
- #121
> Releasing 2.2.3

- CHANGELOG.md
- octoprint_octorelay/static/js/octorelay.js
- octoprint_octorelay/templates/octorelay_navbar.jinja2
- setup.py
- ts/__snapshots__/octorelay.spec.ts.snap
- ts/octorelay.spec.ts
- ts/octorelay.ts
- ts/yarn.lock
> Releasing 2.2.4

- .github/workflows/CI.yaml
- .pylintrc
- CHANGELOG.md
- README.md
- octoprint_octorelay/__init__.py
- octoprint_octorelay/const.py
- octoprint_octorelay/migrations.py
- tests/test_driver.py
- tests/test_init.py
- tests/test_migrations.py
Closes #45 
This PR fixes an issue, but it also introduces a feature — settings versioning and migrations.
> Disabling all relays by default.

- .github/workflows/CI.yaml
- .pylintrc
- CHANGELOG.md
- README.md
- octoprint_octorelay/__init__.py
- octoprint_octorelay/const.py
- octoprint_octorelay/migrations.py
- tests/test_driver.py
- tests/test_init.py
- tests/test_migrations.py
> 🚀 Releasing 3.2.0

- .gitignore
- octoprint_octorelay/__init__.py
I tried before, but it didn't work when tests were in the same directory with the plugin module.
> Relative imports

- octoprint_octorelay/templates/octorelay_settings.jinja2
> Consistent indents for settings template

- .github/workflows/CI.yaml
- tests/snapshots/snap_test_templates.py
- tests/test_templates.py
I'm going to adjust the settings template and before that I wanna have snapshot-tests of it.
> Snapshot testing for templates

- octoprint_octorelay/__init__.py
- tests/test_init.py
Closes #175 
- Also fixing invalid mock resetting method used in tests
> Avoid requesting disabled relay state for UI

- octoprint_octorelay/__init__.py
- tests/test_init.py
> Prevent toggling disabled relays.

- octoprint_octorelay/templates/octorelay_navbar.jinja2
- tests/snapshots/snap_test_templates.py
- ts/OctoPrint.d.ts
- ts/__snapshots__/octorelay.spec.ts.snap
- ts/octorelay.spec.ts
- ts/octorelay.ts
> Restore tooltip after closing popover

- octoprint_octorelay/__init__.py
- tests/test_init.py
> Add missing UI update

- octoprint_octorelay/__init__.py
- octoprint_octorelay/const.py
- octoprint_octorelay/migrations.py
- octoprint_octorelay/templates/octorelay_settings.jinja2
- tests/snapshots/snap_test_templates.py
- tests/test_init.py
- tests/test_migrations.py
- ts/bindings.spec.ts
This will be required for #189 #153
> Feat: specify the printer relay

- README.md
- octoprint_octorelay/static/css/octorelay.css
- octoprint_octorelay/templates/octorelay_settings.jinja2
- tests/snapshots/snap_test_templates.py
> UI: minor clarifications

- octoprint_octorelay/__init__.py
- tests/test_init.py
Closes #205 
Addition to #213 
Revealed during the QA in #209
> Ensure UI update when event just cancels tasks

- ui/bindings.spec.ts
- ui/package.json
- ui/vitest.config.ts
- ui/yarn.lock
Runs faster with less dependencies
> Use HappyDOM

- ui/model/OctoRelayModel.ts
> Fix `self` to `this` alias in model

- octoprint_octorelay/driver.py
It does not need to be the class method
> Restore standalone `xor`

- ui/eslint.config.js
- ui/package.json
- ui/yarn.lock
> Replacing ESLint `import-x` plugin with `allowed-dependencies`

- .github/workflows/CI.yaml
- .github/workflows/release.yaml
- octoprint_octorelay/task.py
- ui/__snapshots__/integration.spec.ts.snap
- ui/integration.spec.ts
- ui/package.json
- ui/vitest.config.ts
Some UI libraries are going to be upgraded, so I'd like to keep track on what is happening to the bundle in an automated way.
> Integration test

- README.md
Fixes #313 
Added note to 5.0.2 release again to avoid confusion
> Readme: direct link to v4 release

- ui/__snapshots__/qa.spec.ts.snap
- ui/helpers/countdown.spec.ts
- ui/helpers/countdown.ts
> Fix countdown localization issue

- octoprint_octorelay/driver.py
Regarding https://github.com/borisbu/OctoRelay/issues/263#issuecomment-2241546096
Fixes https://github.com/borisbu/OctoRelay/issues/299
Opened a discussion here: https://github.com/gpiozero/gpiozero/discussions/1175
Could someone help me to test this branch on their Raspberry Pi running Bookworm, please?
Let me know and I'll publish a prerelease.
> Feat: no pin lock, avoid exclusive reservations

- ui/styles/octorelay.scss
https://sass-lang.com/documentation/breaking-changes/import/
replacing with `use`
> Fix SASS `import` directive deprecation

- .github/workflows/CI.yaml
- .github/workflows/release.yaml
https://github.com/OctoPrint/OctoPrint/releases/tag/1.11.0
> Support OctoPrint 1.11
